/**
 * `cf-lite add agents` (also run by `cf-lite init`): the files that tell a coding agent how this app is built.
 * ONE source (`AI_SOURCE`) is rendered into every target, so they cannot drift apart:
 *   AGENTS.md                          the canonical text (Copilot CLI, Codex, Cursor, ... read it)
 *   CLAUDE.md                          `@AGENTS.md` import (Claude Code), appended to an existing file, never rewritten
 *   .claude/skills/cf-lite/SKILL.md    Claude Code skill (same rules, with frontmatter)
 *   .github/copilot-instructions.md    Copilot instructions (same rules, in short form)
 * Same contract as every `add-*` file: idempotent, never overwrites a file you own, prints what it did.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { declaredBindings } from "./doctor.js";
import { parseJsonc } from "./wrangler-edit.js";

export interface AppFacts { name: string; ui: string; bindings: string[] }

/** The single source: every target below is a rendering of this object. */
export const AI_SOURCE = {
  rules: [
    "Use the `cfl` CLI (alias of `cf-lite`) for anything it can do; do not hand-write `wrangler.jsonc` entries it generates. Every `cfl add <target>` is idempotent and takes `--dry-run` (prints the diff, changes nothing) - run it first.",
    "Files are the router: pages in `app/routes/`, Hono API routes in `server/api/`, cron in `server/cron/`, queue consumers in `server/queues/`, middleware in `server/middleware.ts`. Do not register routes by hand.",
    "Bindings are declared in `wrangler.jsonc` and typed in `interface Env`; after changing bindings run `cfl types`. Never read secrets from the repo: `.dev.vars` is local only, list names in `.dev.vars.example`, push with `cfl secrets push`.",
    "Components get states in a sibling `*.states.ts` (`defineStates` from `cf-lite/preview`); they render at `/__preview` in dev and `cfl export` writes HTML fragments. `MOCK=1` / `cfl dev --mock` serves `mocks/**` instead of real APIs. Neither ships in a production build.",
    "Run `cfl doctor` after every config change and before committing; `cfl doctor --fix` applies the safe autofixes. Fix every error; a warning needs a reason.",
    "Never deploy, push secrets with `--force`, or run `--remote` database commands without being asked.",
  ],
  commands: [
    ["cfl dev [--mock]", "dev server (add --mock to answer from `mocks/`)"],
    ["cfl add <target> [--dry-run]", "add a binding, adapter or feature (d1, kv, r2, queue, cron, auth, tailwind, ...)"],
    ["cfl g page|api|component|test <name> [--dry-run] [--json]", "generate files that follow the conventions (idempotent, never overwrites)"],
    ["cfl mcp", "MCP server (stdio) exposing the same generators/`add`/`doctor` as typed tools; prefer it over hand-editing"],
    ["cfl db new <name> | apply | status", "D1 migrations"],
    ["cfl doctor [--fix] [--strict]", "static checks (CFL001-CFL018), `--fix` for the safe subset"],
    ["cfl types", "regenerate `Env` and typed routes"],
    ["cfl build", "production build"],
    ["cfl deploy --dry-run", "show the deploy plan; deploy only on request"],
  ] as Array<[string, string]>,
  docs: "https://github.com/cf-lite/cf-lite/tree/main/docs",
};

const facts = (f: AppFacts) =>
  `This is \`${f.name}\`, a cf-lite app (Vite + Hono on Cloudflare Workers static assets; no runtime framework). UI: ${f.ui}. Bindings: ${f.bindings.length ? f.bindings.join(", ") : "none yet"}.`;
const rules = () => AI_SOURCE.rules.map((r) => `- ${r}`).join("\n");
const commands = () => AI_SOURCE.commands.map(([c, d]) => `- \`${c}\` - ${d}`).join("\n");

const MARK = "<!-- generated by `cfl add agents`; edit freely, it is never overwritten -->";

export function renderAgents(f: AppFacts): string {
  return `# AGENTS.md\n\n${MARK}\n\n${facts(f)}\n\n## Rules\n\n${rules()}\n\n## Commands\n\n${commands()}\n\nDocs: ${AI_SOURCE.docs} (conventions.md, doctor.md, recipes.md).\n`;
}
export function renderSkill(f: AppFacts): string {
  return `---\nname: cf-lite\ndescription: Work on this cf-lite (Cloudflare Workers) app - add bindings, routes, jobs, components; use when the task touches wrangler.jsonc, app/routes, server/api, mocks, or deploys.\n---\n\n${MARK}\n\n${facts(f)}\n\n## Rules\n\n${rules()}\n\n## Commands\n\n${commands()}\n`;
}
export function renderCopilot(f: AppFacts): string {
  return `${MARK}\n\n${facts(f)} The full instructions are in AGENTS.md; the essentials:\n\n${rules()}\n\n${commands()}\n`;
}

/** What the app has today (from package.json / vite.config / wrangler.jsonc); never throws. */
export function appFacts(dir: string): AppFacts {
  let name = "this app";
  try { name = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")).name || name; } catch { /* no package.json */ }
  const vc = ["vite.config.ts", "vite.config.mts", "vite.config.js"].map((f) => join(dir, f)).find(existsSync);
  const cfg = vc ? readFileSync(vc, "utf8") : "";
  const ui = ["react", "preact", "vue", "svelte"].find((u) => cfg.includes(`@cf-lite/${u}`)) ?? "none (plain server-rendered HTML)";
  let bindings: string[] = [];
  const w = ["wrangler.jsonc", "wrangler.json"].map((f) => join(dir, f)).find(existsSync);
  if (w) { try { bindings = [...declaredBindings(parseJsonc(readFileSync(w, "utf8")))].sort(); } catch { /* unparsable: doctor reports it */ } }
  return { name, ui, bindings };
}

export function addAgents(dir: string, log: (m: string) => void = () => {}): { changed: string[] } {
  if (!existsSync(join(dir, "package.json"))) throw new Error("run it in your app directory (no package.json here)");
  const f = appFacts(dir);
  const changed: string[] = [];
  const create = (rel: string, body: string) => {
    const p = join(dir, rel);
    if (existsSync(p)) { log(`  keep   ${rel} (exists)`); return; }
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, body);
    changed.push(rel); log(`  create ${rel}`);
  };
  create("AGENTS.md", renderAgents(f));
  create(".claude/skills/cf-lite/SKILL.md", renderSkill(f));
  create(".github/copilot-instructions.md", renderCopilot(f));
  const cm = join(dir, "CLAUDE.md");
  if (!existsSync(cm)) create("CLAUDE.md", "@AGENTS.md\n");
  else {
    const t = readFileSync(cm, "utf8");
    if (/^@AGENTS\.md\s*$/m.test(t)) log("  keep   CLAUDE.md (already imports AGENTS.md)");
    else { writeFileSync(cm, t + (t && !t.endsWith("\n") ? "\n" : "") + "\n@AGENTS.md\n"); changed.push("CLAUDE.md"); log("  edit   CLAUDE.md (+ @AGENTS.md import)"); }
  }
  return { changed };
}
