/**
 * Renders the generated files under .cf-lite/ from convention contributors (see conventions/types.ts, docs/conventions.md).
 * Real .ts files (not virtual modules) so tsc sees real types. This file knows the *shape* of app.ts / handlers.ts, never a convention.
 */
import type { UiAdapter } from "./adapter.js";
import { apiConvention, pagesConvention, genRoutes } from "./conventions/index.js";
import type { Convention, Emission, HandlerSlots } from "./conventions/index.js";
import type { ApiRoute, PageRoute } from "./scan.js";

export { genRoutes };

const cat = (es: Emission[], k: "preImports" | "imports" | "declarations" | "api" | "appPre" | "app" | "exports") => es.flatMap((e) => e[k] ?? []);

/** Result of running every contributor. */
export interface Generated {
  /** name -> full content of each file under .cf-lite/ (app.ts always; handlers.ts only when a contributor provides a handler). */
  files: Record<string, string>;
  /** Entries each contributor's `scan` returned. */
  entries: Record<string, unknown>;
  workerFirst: string[];
  /** Worker-first globs that only `vite dev` needs (dev tools). */
  devWorkerFirst: string[];
  checks: Array<(wrangler: Record<string, unknown>) => string[]>;
}

/** Hono app: /api/* plus whatever the contributors mount. Exports ApiType for hono/client. */
export function renderApp(es: Emission[]): string {
  const L: string[] = ["// generated by cf-lite — do not edit", `import { Hono } from "hono";`, ...cat(es, "preImports"), ...cat(es, "imports")];
  const decl = cat(es, "declarations");
  if (decl.length) L.push("", ...decl);
  L.push("", "export const api = new Hono<{ Bindings: Env }>()", ...cat(es, "api"));
  L.push(";", "export type ApiType = typeof api;", "", "export const app = new Hono<{ Bindings: Env }>()", ...cat(es, "appPre"), `  .route("/api", api)`, ...cat(es, "app"));
  L.push(";", ...cat(es, "exports"), "export default app;", "");
  return L.join("\n");
}

/** `.cf-lite/handlers.ts`, or null when no contributor supplies a non-fetch handler (then the file does not exist: zero bytes). */
export function renderHandlers(es: Emission[]): string | null {
  const slots: (keyof HandlerSlots)[] = ["queue", "scheduled", "email", "tail", "trace"];
  const hs = es.flatMap((e) => (e.handlers ? [e.handlers] : []));
  const imports = hs.flatMap((h) => h.imports ?? []);
  const body: string[] = [];
  for (const s of slots) {
    const defs = hs.map((h) => h[s]).filter((x): x is string => !!x);
    if (defs.length > 1) throw new Error(`cf-lite: more than one convention provides the \`${s}\` handler - compose them in one contributor.`);
    if (defs.length) body.push(`  ${s}: ${defs[0]},`);
  }
  if (!body.length) return null;
  return `// generated by cf-lite — do not edit\n// Use in server/worker.ts: export default { fetch, ...handlers } satisfies ExportedHandler<Env>;\n${imports.join("\n")}${imports.length ? "\n" : ""}\nexport const handlers = {\n${body.join("\n")}\n} satisfies ExportedHandler<Env>;\n`;
}

/** Run every contributor (scan, then emit in order) and render the files. */
export function runConventions(root: string, adapter: UiAdapter | undefined, conventions: Convention<any>[]): Generated {
  const names = new Set<string>();
  for (const c of conventions) {
    if (names.has(c.name)) throw new Error(`cf-lite: duplicate convention "${c.name}"`);
    names.add(c.name);
  }
  const entries: Record<string, unknown> = {};
  for (const c of conventions) entries[c.name] = c.scan({ root, adapter });
  const emissions = conventions.map((c) => c.emit(entries[c.name], { root, adapter, entries }));
  const files: Record<string, string> = { "app.ts": renderApp(emissions) };
  for (const e of emissions) for (const [n, body] of Object.entries(e.files ?? {})) {
    if (n in files) throw new Error(`cf-lite: two conventions generate .cf-lite/${n}`);
    files[n] = body;
  }
  const handlers = renderHandlers(emissions);
  if (handlers !== null) files["handlers.ts"] = handlers;
  return {
    files,
    entries,
    workerFirst: [...new Set(emissions.flatMap((e) => e.workerFirst ?? []))],
    devWorkerFirst: [...new Set(emissions.flatMap((e) => e.devWorkerFirst ?? []))],
    checks: emissions.flatMap((e) => e.checks ?? []),
  };
}

/** Compat: app.ts for an already-scanned api/page list (what `generate()` does for the built-in conventions). */
export function genApp(api: ApiRoute[], pages: PageRoute[], ui?: { server: string }): string {
  const ctx = { root: "", adapter: ui as UiAdapter | undefined, entries: {} };
  return renderApp([apiConvention.emit(api, ctx), pagesConvention.emit(pages, ctx)]);
}
