// Per-adapter numbers: builds the same app (examples/site*: static / + SPA routes + nested layouts + head + one hydrated SSR route)
// in react / preact / vue / svelte / solid (+ the htmx/Alpine preset) and reports what each UI adapter costs. No latency here (local launchers are floor-bound, see
// RESULTS.md caveat 1); these are exact byte counts from the built output.   node bench/adapters.mjs  ->  bench/RESULTS-adapters.md
import { spawnSync } from "node:child_process";
import { readFileSync, readdirSync, statSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

const root = new URL("../", import.meta.url).pathname;
const cli = join(root, "packages/cf-lite/dist/cli.js");
const UIS = [["react", "site"], ["preact", "site-preact"], ["vue", "site-vue"], ["svelte", "site-svelte"], ["solid", "site-solid"], ["htmx", "site-htmx"]];
const gz = (b) => gzipSync(b, { level: 9 }).length;
const kib = (n) => (n / 1024).toFixed(1) + " KiB";
const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });

const rows = [];
for (const [ui, dir] of UIS) {
  const cwd = join(root, "examples", dir);
  rmSync(join(cwd, "dist"), { recursive: true, force: true });
  const t = Date.now();
  const b = spawnSync(process.execPath, [cli, "build"], { cwd, encoding: "utf8" });
  if (b.status !== 0) throw new Error(`${ui}: build failed\n${b.stdout}${b.stderr}`);
  const secs = (Date.now() - t) / 1000;
  const workerDir = join(cwd, "dist", readdirSync(join(cwd, "dist")).find((n) => n !== "client"));
  const wjs = walk(workerDir).filter((f) => /\.m?js$/.test(f));
  const worker = { raw: wjs.reduce((n, f) => n + statSync(f).size, 0), gzip: wjs.reduce((n, f) => n + gz(readFileSync(f)), 0) };
  const client = join(cwd, "dist/client");
  const assets = walk(client).filter((f) => f.endsWith(".js"));
  const all = assets.reduce((n, f) => n + gz(readFileSync(f)), 0);
  // JS a hydrated SSR page downloads up front: the entry script + modulepreloads named in the shell (route chunks load on demand)
  const shell = readFileSync(join(client, ui === "htmx" ? "index.html" : "_shell.tpl"), "utf8"); // htmx preset: no SSR route, so the shell is index.html
  const refs = [...shell.matchAll(/(?:src|href)="(\/assets\/[^"]+\.js)"/g)].map((m) => m[1]);
  const upfront = refs.reduce((n, r) => n + gz(readFileSync(join(client, r))), 0);
  const staticJs = ui === "htmx" ? "n/a (no prerender; shell always loads htmx+Alpine)" : /<script/.test(readFileSync(join(client, "about/index.html"), "utf8")) ? "has JS" : "0";
  rows.push({ ui, worker, all, upfront, staticJs, secs });
}
const t = (f) => rows.map(f).join(" | ");
const md = `# Per-adapter benchmark (same app in five UI frameworks + the htmx/Alpine preset)

Generated by \`node bench/adapters.mjs\` on ${new Date().toISOString()} (Node ${process.version}). App = \`examples/site*\`: static \`/\` and \`/about\` (prerendered, zero JS), SPA routes under nested layouts,
\`head\` exports, a hydrated SSR route \`/blog/:slug\` with a loader, a typed \`hc<ApiType>\` call. Worker bundles are **minified** (\`cf-lite\` default since 0.3).
Exact byte counts from the build output (gzip level 9 per file, summed). Versions float (react ${v("react")}, preact ${v("preact")}, vue ${v("vue")}, svelte ${v("svelte")}, solid ${v("solid-js")}, htmx ${v("htmx.org")} + alpinejs ${v("alpinejs")}).

| metric | ${rows.map((r) => r.ui).join(" | ")} |
|---|${rows.map(() => "---").join("|")}|
| Worker code, gzip (SSR route + layouts + API) | ${t((r) => kib(r.worker.gzip))} |
| Worker code, raw | ${t((r) => kib(r.worker.raw))} |
| Client JS on a hydrated SSR page, up front (entry + preloads), gzip | ${t((r) => kib(r.upfront))} |
| Client JS, all chunks incl. lazily loaded routes, gzip | ${t((r) => kib(r.all))} |
| JS on a static page (\`/about\`) | ${t((r) => r.staticJs)} |
| \`cf-lite build\` wall time (cold dist, warm deps) | ${t((r) => r.secs.toFixed(1) + " s")} |

## Reading it

* **Worker size** is what a UI costs on the SSR path only. An app with no \`render = "ssr"\` route bundles no renderer at all (core-only Worker: see \`bench/RESULTS.md\`, 7.2 KiB gzip minified for the API-only bench app).
* Svelte's Worker is the smallest, plausibly because Svelte compiles components to string-concatenating functions (no runtime VDOM renderer) and SSR is synchronous (no streaming machinery). Vue ships its renderer + reactivity (\`vue/server-renderer\` + \`@vue/runtime-core\`); React ships \`react-dom/server\` (Suspense/streaming, the largest).
* **Solid** compiles JSX to fine-grained DOM instructions; its Worker carries \`solid-js/web\`'s server build (\`renderToStream\`) and its client runtime is small because there is no virtual DOM.
* **htmx + Alpine is not the same app.** \`site-htmx\` (renderer \`"none"\`) reproduces the pages as server-rendered Hono fragments, so its Worker holds the fragment routes (there is no SSR-route/prerender machinery and no layouts system) and its client JS is htmx + Alpine shipped on every page, including the first. Compare it for order of magnitude, not as a like-for-like row.
* **Minification** (field-notes item 4, fixed in 0.3): the same React SSR app was ~111 KiB gzip unminified (0.2.x, \`examples/site\` measured in design.md) and 73.5 KiB gzip minified in the \`bench/apps/cf-lite-ssr\` app (108.6 → 73.5 KiB; preact 29.0 → 17.5 KiB; API-only 14.9 → 7.2 KiB — see the v0.3 addendum at the end of \`bench/RESULTS.md\`; byte counts from a 1-run local \`bench/run.sh\` on 2026-09-30).
* **Not measured here:** request latency (local launchers add a ~15 ms floor, meaning nothing per adapter), cold-start parse time (expected to follow Worker size, not measured), hydration time in a browser.
* Feature differences that affect the numbers are listed in \`docs/adapters.md\` §3 (Svelte has no streaming; Preact streams sequentially; React streams with Suspense).
`;
function v(p) { try { return JSON.parse(readFileSync(join(root, "node_modules", p, "package.json"), "utf8")).version; } catch { return "?"; } }
writeFileSync(join(root, "bench/RESULTS-adapters.md"), md);
console.log(md);
