// generated by cf-lite — do not edit
import { Hono } from "hono";
import { cacheRoute } from "cf-lite/modules/cache";
import { ssr } from "cf-lite/server";
import * as ui from "@cf-lite/react/server";
import a0 from "../server/api/cache";
import a1 from "../server/api/hello";
import a2 from "../server/api/room";
import * as s0 from "../app/routes/cached/[id]";
import * as s1 from "../app/routes/cached-fn/[id]";
import * as s2 from "../app/routes/posts/[id]";
import * as l0 from "../app/routes/_layout";
import * as l1 from "../app/routes/posts/_layout";

export const api = new Hono<{ Bindings: Env }>()
  .route("/cache", a0)
  .route("/hello", a1)
  .route("/room", a2)
;
export type ApiType = typeof api;

export const app = new Hono<{ Bindings: Env }>()
  .route("/api", api)
  .get("/cached/:id", cacheRoute(s0 as never, ssr(s0 as never, { ui, hydrate: false, layouts: [l0] as never })))
  .get("/cached-fn/:id", cacheRoute(s1 as never, ssr(s1 as never, { ui, hydrate: false, layouts: [l0] as never })))
  .get("/posts/:id", ssr(s2 as never, { ui, hydrate: false, layouts: [l0, l1] as never }))
;
export default app;
