// generated by cf-lite — do not edit
import type { ClientRoute } from "cf-lite/client";
export const routes: ClientRoute[] = [
  { path: "/cached/:id", render: "ssr", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/cached/[id]") },
  { path: "/cached-fn/:id", render: "ssr", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/cached-fn/[id]") },
  { path: "/posts/:id", render: "ssr", hydrate: false, layouts: [() => import("../app/routes/_layout"), () => import("../app/routes/posts/_layout")], load: () => import("../app/routes/posts/[id]") },
  { path: "/about", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/about") },
  { path: "/counter", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/counter") },
  { path: "/", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/index") },
];
