// generated by cf-lite — do not edit
import type { ClientRoute } from "cf-lite/client";
export const routes: ClientRoute[] = [
  { path: "/app/dashboard", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout.svelte"), () => import("../app/routes/app/_layout.svelte")], load: () => import("../app/routes/app/dashboard.svelte") },
  { path: "/app/settings", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout.svelte"), () => import("../app/routes/app/_layout.svelte")], load: () => import("../app/routes/app/settings.svelte") },
  { path: "/blog/:slug", render: "ssr", hydrate: true, layouts: [() => import("../app/routes/_layout.svelte"), () => import("../app/routes/blog/_layout.svelte")], load: () => import("../app/routes/blog/[slug].svelte") },
  { path: "/about", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout.svelte")], load: () => import("../app/routes/about.svelte") },
  { path: "/", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout.svelte")], load: () => import("../app/routes/index.svelte") },
];
