// generated by cf-lite — do not edit
import type { ClientRoute } from "cf-lite/client";
export const routes: ClientRoute[] = [
  { path: "/app/dashboard", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout"), () => import("../app/routes/app/_layout")], load: () => import("../app/routes/app/dashboard") },
  { path: "/app/settings", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout"), () => import("../app/routes/app/_layout")], load: () => import("../app/routes/app/settings") },
  { path: "/blog/:slug", render: "ssr", hydrate: true, layouts: [() => import("../app/routes/_layout"), () => import("../app/routes/blog/_layout")], load: () => import("../app/routes/blog/[slug]") },
  { path: "/about", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/about") },
  { path: "/", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout")], load: () => import("../app/routes/index") },
];
