// generated by cf-lite — do not edit
import { Hono } from "hono";
import a0 from "../server/api/hello";
import a1 from "../server/api/ui";

export const api = new Hono<{ Bindings: Env }>()
  .route("/hello", a0)
  .route("/ui", a1)
;
export type ApiType = typeof api;

export const app = new Hono<{ Bindings: Env }>()
  .route("/api", api)
;
export default app;
