// generated by cf-lite — do not edit
import type { ClientRoute } from "cf-lite/client";
export const routes: ClientRoute[] = [
  { path: "/app/dashboard", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout.vue"), () => import("../app/routes/app/_layout.vue")], load: () => import("../app/routes/app/dashboard.vue") },
  { path: "/app/settings", render: "spa", hydrate: false, layouts: [() => import("../app/routes/_layout.vue"), () => import("../app/routes/app/_layout.vue")], load: () => import("../app/routes/app/settings.vue") },
  { path: "/blog/:slug", render: "ssr", hydrate: true, layouts: [() => import("../app/routes/_layout.vue"), () => import("../app/routes/blog/_layout.vue")], load: () => import("../app/routes/blog/[slug].vue") },
  { path: "/about", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout.vue")], load: () => import("../app/routes/about.vue") },
  { path: "/", render: "static", hydrate: false, layouts: [() => import("../app/routes/_layout.vue")], load: () => import("../app/routes/index.vue") },
];
