// generated by cf-lite — do not edit
import { Hono } from "hono";
import { ssr } from "cf-lite/server";
import * as ui from "@cf-lite/solid/server";
import a0 from "../server/api/hello";
import * as s0 from "../app/routes/blog/[slug]";
import * as l0 from "../app/routes/_layout";
import * as l1 from "../app/routes/blog/_layout";

export const api = new Hono<{ Bindings: Env }>()
  .route("/hello", a0)
;
export type ApiType = typeof api;

export const app = new Hono<{ Bindings: Env }>()
  .route("/api", api)
  .get("/blog/:slug", ssr(s0 as never, { ui, hydrate: true, layouts: [l0, l1] as never }))
;
export default app;
