// Shared by scripts/gen-llms.mjs (generate / --check) and scripts/docs-check.mjs, and unit-tested (packages/cf-lite/test/llms.test.ts).
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SUMMARY = "Vite plugin + CLI for Cloudflare Workers apps: file routes, Hono API, opt-in modules (auth, storage, jobs, ISR, RSC, preview). Open source (MIT), version 0.x.";
const REPO = "https://github.com/cf-lite/cf-lite/blob/main";

/** First `# ` heading and first prose paragraph (links flattened, markup stripped, <= 160 chars) of a markdown source. */
export function describe(md) {
  const body = md.replace(/```[\s\S]*?```/g, "");
  const title = (body.match(/^# (.+)$/m)?.[1] ?? "").replace(/`/g, "").trim();
  const para = body.split(/\n\s*\n/).map((b) => b.trim()).find((b) => b && !/^(#|\||[-*>]|\d+\.|<)/.test(b)) ?? "";
  let d = para.replace(/\n+/g, " ").replace(/\[([^\]]+)\]\([^)]*\)/g, "$1").replace(/[`*]/g, "").replace(/\s+/g, " ").trim();
  if (d.length > 160) d = d.slice(0, 157).replace(/\s+\S*$/, "") + "...";
  return { title, desc: d };
}

/** Deterministic llms.txt (llmstxt.org shape: H1, blockquote summary, H2 sections of `- [title](url): desc`). */
export function buildLlms(docsDir = join(root, "docs")) {
  const names = readdirSync(docsDir).filter((f) => f.endsWith(".md")).sort();
  const sections = [
    ["Start here", ["getting-started", "troubleshooting", "recipes", "conventions", "dx"]],
    ["Reference", null], // everything not listed elsewhere
    ["Project status (not API)", ["roadmap-1.0", "roadmap-dx", "rc-status", "field-notes", "next-parity", "stability", "upgrading"]],
  ];
  const used = new Set(["README"]);
  const line = (n) => { const { title, desc } = describe(readFileSync(join(docsDir, `${n}.md`), "utf8")); return `- [${title || n}](${REPO}/docs/${n}.md)${desc ? `: ${desc}` : ""}`; };
  const out = ["# cf-lite", "", `> ${SUMMARY}`, "",
    "Generated by `bun run llms:gen` from `docs/`; do not edit. Agent rules: [AGENTS.md](" + REPO + "/AGENTS.md).", ""];
  for (const [h, list] of sections) {
    const picks = list ? list.filter((n) => names.includes(`${n}.md`)) : names.map((f) => f.slice(0, -3)).filter((n) => !sections.some(([, l]) => l?.includes(n)) && n !== "README");
    picks.forEach((n) => used.add(n));
    out.push(`## ${h}`, "", ...picks.map(line), "");
  }
  return out.join("\n").replace(/\n+$/, "\n");
}

/** Highest CFL code `doctor.ts` can emit, plus the set of all of them. */
export function doctorCodes() {
  const src = readFileSync(join(root, "packages/cf-lite/src/doctor.ts"), "utf8");
  return [...new Set(src.match(/CFL\d{3}/g) ?? [])].sort();
}

/** Doc-drift problems: stale `CFLnnn-CFLmmm` ranges and doctor codes with no doctor.md section. */
export function codeDrift(files, codes = doctorCodes()) {
  const max = codes[codes.length - 1], bad = [];
  for (const [f, text] of files) {
    for (const m of text.matchAll(/CFL001\s*(?:-|–|to)\s*(?:CFL)?(\d{3})/g)) if (`CFL${m[1]}` !== max) bad.push(`${f}: range ends at CFL${m[1]}, doctor.ts emits up to ${max}`);
  }
  const page = files.find(([f]) => f === "docs/doctor.md")?.[1] ?? "";
  for (const c of codes) if (!new RegExp(`^## ${c}$`, "m").test(page)) bad.push(`docs/doctor.md: no "## ${c}" section`);
  return bad;
}
