/**
 * `server/do/<name>.ts` -> Worker-entry re-exports of the Durable Object classes (`.cf-lite/do-classes.ts`) and typed namespace helpers
 * (`.cf-lite/do.ts`: `durableObjects.<name>.get(id)` / `.fetch(id, request)`).
 *
 *   export default class Chat extends HibernatingRoom<Env> { ... }     // or a SqlDO / any DurableObject subclass
 *   export const className = "Chat";       // optional (default: PascalCase of the file name) - must equal wrangler `class_name`
 *   export const binding = "CHAT";         // optional (default: <FILE_NAME> upper-snake)
 *
 * In `server/worker.ts`:  `export * from "../.cf-lite/do-classes";`   (`cf-lite add do <name>` scaffolds file + wrangler entries).
 */
import { defineConvention } from "./types.js";
import { asArray, hasDefault, imp, pascal, readString, scanJobDir, upperSnake } from "./jobs-util.js";

export interface DoEntry { file: string; name: string; className: string; binding: string; hasDefault: boolean }

export const doConvention = defineConvention<DoEntry[]>({
  name: "do",
  scan: ({ root }) =>
    scanJobDir(root, "do").map((f) => ({
      file: f.file,
      name: f.name,
      className: readString(f.src, "className") ?? pascal(f.name),
      binding: readString(f.src, "binding") ?? upperSnake(f.name),
      hasDefault: hasDefault(f.src),
    })),
  emit: (ds) => {
    if (!ds.length) return {};
    const seen = new Map<string, string>();
    for (const d of ds) {
      if (seen.has(d.className)) throw new Error(`cf-lite: ${d.file} and ${seen.get(d.className)} both export Durable Object class "${d.className}"`);
      seen.set(d.className, d.file);
    }
    const active = ds.filter((d) => d.hasDefault);
    const classes = [
      "// generated by cf-lite — do not edit",
      "// Durable Object classes must be exported from the Worker entry: in server/worker.ts add  export * from \"../.cf-lite/do-classes\";",
      ...active.map((d) => `export { default as ${d.className} } from ${JSON.stringify(imp(d.file))};`),
      "",
    ].join("\n");
    const helpers = [
      "// generated by cf-lite — do not edit",
      `import { env } from "cloudflare:workers";`,
      `import { doStub } from "cf-lite/modules/realtime";`,
      "",
      "/** `await durableObjects.chat.fetch(\"lobby\", request)` forwards a WebSocket upgrade; `.get(name)` returns the stub. Bindings come from wrangler `durable_objects`. */",
      "export const durableObjects = {",
      ...active.map((d) => `  ${JSON.stringify(d.name)}: doStub(() => (env as unknown as Env).${d.binding} as DurableObjectNamespace),`),
      "};",
      "",
    ].join("\n");
    return {
      files: { "do-classes.ts": classes, "do.ts": helpers },
      checks: [
        () => ds.filter((d) => !d.hasDefault).map((d) => `${d.file} has no default export (a class extending DurableObject / HibernatingRoom / SqlDO)`),
        (w) => {
          const bindings = asArray((w.durable_objects as { bindings?: unknown } | undefined)?.bindings) as { name?: string; class_name?: string }[];
          const sqlite = new Set<string>(), legacy = new Set<string>();
          for (const m of asArray(w.migrations) as { new_sqlite_classes?: string[]; new_classes?: string[] }[]) {
            for (const c of m.new_sqlite_classes ?? []) sqlite.add(c);
            for (const c of m.new_classes ?? []) legacy.add(c);
          }
          return ds.flatMap((d) => {
            const out: string[] = [];
            const b = bindings.find((x) => x.name === d.binding);
            if (!b) out.push(`${d.file}: wrangler \`durable_objects.bindings\` has no binding "${d.binding}" - run \`cf-lite add do ${d.name}\``);
            else if (b.class_name !== d.className) out.push(`${d.file}: wrangler binding "${d.binding}" has class_name "${b.class_name}" but the generated export is "${d.className}"`);
            if (!sqlite.has(d.className)) out.push(legacy.has(d.className)
              ? `${d.file}: class "${d.className}" is in migrations \`new_classes\` (KV-backed) - SQLite-backed is the default for new classes (\`new_sqlite_classes\`)`
              : `${d.file}: no wrangler migration creates class "${d.className}" (\`{ "tag": "v1", "new_sqlite_classes": ["${d.className}"] }\`) - the first request would fail`);
            return out;
          });
        },
      ],
    };
  },
});
