/**
 * i18n convention (docs/i18n.md): `cfLite({ i18n: { locales, default } })` + pages under `app/routes/[locale]/` ->
 *   - `.cf-lite/i18n.ts` (`export const i18n`, `Locale`, `localizedRoutes`) for pages/layouts to import;
 *   - one Hono middleware in front of the app (`cf-lite/modules/i18n`): detection only for `/` and unprefixed localized paths;
 *   - Worker-first globs for exactly those unprefixed paths (`/`, `/about`, `/posts/*`) - prefixed pages keep being assets/SSR as usual.
 * Not a built-in (it needs the user's config): `generate()` prepends it when `i18n` is set.
 */
import type { PageRoute } from "../scan.js";
import { toWorkerGlobs } from "../scan.js";
import { defineI18n, type I18nConfig } from "../modules/i18n.js";
import { defineConvention } from "./types.js";

export const I18N_NAME = "i18n";
const isLocalized = (p: PageRoute) => p.path === "/:locale" || p.path.startsWith("/:locale/");

export function i18nConvention(cfg: I18nConfig) {
  return defineConvention<I18nConfig>({
    name: I18N_NAME,
    scan: () => defineI18n(cfg),
    emit: (c, ctx) => {
      const pages = ((ctx.entries.pages as PageRoute[] | undefined) ?? []).filter(isLocalized);
      for (const p of pages) if (p.render === "static" && !p.hasPaths) throw new Error(`cf-lite: i18n: ${p.file} is static: export \`paths()\` returning localeParams(i18n) so it is prerendered once per locale.`);
      const routes = pages.map((p) => p.path).sort();
      const unprefixed = pages.map((p) => "/" + p.path.split("/").filter(Boolean).slice(1).join("/"));
      const home = pages.find((p) => p.path === "/:locale");
      const file = `// generated by cf-lite — do not edit\nimport type { I18nConfig } from "cf-lite/modules/i18n";\n\nexport const i18n = ${JSON.stringify(c, null, 2)} as const satisfies I18nConfig;\nexport type Locale = (typeof i18n.locales)[number];\nexport const localizedRoutes = ${JSON.stringify(routes)} as const;\n`;
      return {
        files: { "i18n.ts": file },
        imports: [`import { i18nMiddleware } from "cf-lite/modules/i18n";`, `import { i18n } from "./i18n";`],
        appPre: [`  .use("*", i18nMiddleware(i18n, { routes: ${JSON.stringify(routes)}${home?.render === "static" ? ", rootSlash: true" : ""} }) as never)`],
        workerFirst: ["/", ...unprefixed.flatMap(toWorkerGlobs)],
        checks: [() => (routes.length ? [] : ["i18n: `cfLite({ i18n })` is set but there is no page under app/routes/[locale]/ - nothing to localize"])],
      };
    },
  });
}
