/**
 * ISR as a route convention: `export const isr = { maxAge, swr?, tags? }` in an `app/routes/**` ssr page.
 * pages.ts wraps the page's GET handler (`isrRoute`); this contributor adds the rest of the Worker wiring:
 *   - `isrOrigin()` middleware (the queue consumer needs the public origin),
 *   - `POST /api/_isr/revalidate` (`isrRevalidate()`, bearer `ISR_REVALIDATE_TOKEN`, closed with 503 when unset),
 *   - wrangler checks for the `ISR_BUCKET` R2 binding and the `isr` queue producer/consumer.
 * The queue consumer itself is generated by conventions/queues.ts unless `server/queues/isr.ts` exists (docs/isr.md).
 * Emits nothing when no page exports `isr`.
 */
import type { PageRoute } from "../scan.js";
import { defineConvention } from "./types.js";
import { asArray } from "./jobs-util.js";

export const isrConvention = defineConvention<null>({
  name: "isr",
  scan: () => null,
  emit: (_e, ctx) => {
    const pages = ((ctx.entries["pages"] as PageRoute[] | undefined) ?? []).filter((p) => p.hasIsr && (p.render === "ssr" || p.render === "rsc" || p.ssrFallback));
    if (!pages.length) return {};
    return {
      preImports: [`import { isrOrigin, isrRevalidate } from "cf-lite/modules/isr";`],
      api: [`  .post("/_isr/revalidate", isrRevalidate())`],
      appPre: [`  .use(isrOrigin())`],
      checks: [
        (w) => {
          const out: string[] = [];
          const r2 = asArray(w.r2_buckets) as { binding?: string }[];
          if (!r2.some((b) => b.binding === "ISR_BUCKET")) out.push(`${pages[0].file} exports \`isr\` but wrangler \`r2_buckets\` has no "ISR_BUCKET" binding - pages are served uncached (BYPASS)`);
          const q = (w.queues ?? {}) as { producers?: unknown };
          if (!(asArray(q.producers) as { binding?: string }[]).some((p) => p.binding === "ISR_QUEUE")) out.push(`\`isr\` routes: no "ISR_QUEUE" queue producer in wrangler - stale copies are refreshed in-process (waitUntil) and revalidateTag() deletes entries instead of enqueuing`);
          return out;
        },
      ],
    };
  },
});
