/**
 * Mock layer (docs/mocks.md): `mocks/**` -> `.cf-lite/mocks.ts` + a dev-only middleware. Active only under `vite dev` with `MOCK=1`
 * (`__CFL_MOCK__`, a compile-time define set by the plugin); in a build `import.meta.env.DEV` is false and the whole module is dropped.
 * Emits nothing without a `mocks/` folder holding at least one mock file.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { scanMocks, type MockFile } from "../mocks.js";
import { defineConvention } from "./types.js";
import { imp } from "./util.js";

export const MOCKS_CONVENTION = "mocks";

export const mocksConvention = defineConvention<MockFile[]>({
  name: MOCKS_CONVENTION,
  scan: ({ root }) => scanMocks(root),
  emit: (routes, ctx) => {
    if (!routes.length) return {};
    const imports: string[] = [];
    const rows = routes.map((r, i) => {
      const base = `{ method: ${JSON.stringify(r.method)}, ${r.host ? `host: ${JSON.stringify(r.host)}, ` : ""}pattern: ${JSON.stringify(r.pattern)}, file: ${JSON.stringify(r.file)}`;
      if (r.kind === "handler") { imports.push(`import * as m${i} from ${JSON.stringify(imp(r.file))};`); return `  ${base}, handler: m${i}.default as never },`; }
      try { JSON.parse(readFileSync(join(ctx.root, r.file), "utf8")); } catch (e) { throw new Error(`cf-lite: ${r.file} is not valid JSON: ${(e as Error).message}`); }
      // imported (not inlined): Vite tracks the JSON file itself, so an edit hot-updates the module without going through a regenerate step
      imports.push(`// @ts-ignore resolveJsonModule is not required of the app\nimport m${i} from ${JSON.stringify("../" + r.file)};`);
      return `  ${base}, json: m${i} },`;
    });
    const file = `// generated by cf-lite — do not edit. Dev only (MOCK=1): loaded behind import.meta.env.DEV, never part of a production build.
import { createMocks } from "cf-lite/modules/mock";
${imports.join("\n")}

export const table = createMocks([
${rows.join("\n")}
]);
`;
    return {
      preImports: [`import type { MiddlewareHandler as MockMiddleware } from "hono";`],
      declarations: [`declare const __CFL_MOCK__: boolean;\n// dev + MOCK=1 only (both are compile-time constants, so a build drops the dynamic import)\nconst mockGate: MockMiddleware = async (c, next) => {\n  if ((import.meta as unknown as { env: { DEV: boolean } }).env.DEV && __CFL_MOCK__) return (await import("./mocks")).table.middleware(c, next);\n  return next();\n};`],
      appPre: [`  .use("*", mockGate)`],
      files: { "mocks.ts": file },
    };
  },
});
