/** `app/routes/**` -> client route table (`routes.ts`) + SSR page handlers in `app.ts`. */
import { scanPages, BOUNDARY_KINDS, type PageRoute } from "../scan.js";
import { defineConvention } from "./types.js";
import { imp } from "./util.js";
import { discoverIslands } from "../vite-islands.js";

/** Hono has no `*?`: `/docs/*` matches `/docs` too, and the handler's own `path` match decides required vs optional. */
const honoPath = (p: string) => p.replace(/\/\*\?$/, "/*");

const NO_UI = "cf-lite: app/routes/ has page files but no UI adapter is configured. Run `bunx cf-lite add react|preact|vue|svelte` (or set `renderer:` in vite.config.ts).";

/** Client route table: consumed by `mount()` from cf-lite/client. */
export function genRoutes(pages: PageRoute[]): string {
  const lazy = (f: string) => `() => import(${JSON.stringify(imp(f))})`;
  const rows = pages.filter((p) => p.render !== "rsc").map((p) => { // rsc routes are full-document navigations: never in the client bundle
    const b = BOUNDARY_KINDS.filter((k) => p[k]).map((k) => `, ${k}: ${lazy(p[k]!)}`).join("");
    return `  { path: ${JSON.stringify(p.path)}, render: ${JSON.stringify(p.render)}, hydrate: ${p.hydrate}, layouts: [${p.layouts.map(lazy).join(", ")}], load: ${lazy(p.file)}${b} },`;
  });
  // A root `_not-found` becomes the last-resort route: unmatched URLs (client navigation, the 404.html shell) render it.
  const root = pages.find((p) => p.notFound && !p.notFound.slice("app/routes/".length).includes("/"))?.notFound;
  if (root) rows.push(`  { path: "/*?", render: "spa", hydrate: false, layouts: [], load: ${lazy(root)}, isNotFound: true },`);
  return `// generated by cf-lite — do not edit\nimport type { ClientRoute } from "cf-lite/client";\nexport const routes: ClientRoute[] = [\n${rows.join("\n")}\n];\n`;
}

/** Opt-in RSC: the rsc-environment entry (Flight producer) + the browser entry that hydrates the document from the inlined Flight stream. */
function rscFiles(rsc: PageRoute[]): Record<string, string> {
  const lazy = (f: string) => `() => import(${JSON.stringify(imp(f))})`;
  const rows = rsc.map((p) => {
    const extra = (["rscError", "rscNotFound", "rscForbidden", "rscUnauthorized"] as const).filter((k) => p[k]).map((k) => `, ${k.slice(3).replace(/^./, (x) => x.toLowerCase())}: ${lazy(p[k]!)}`).join("");
    return `  ${JSON.stringify(p.path)}: { load: ${lazy(p.file)}, layouts: [${(p.rscLayouts ?? []).map(lazy).join(", ")}]${extra} },`;
  }).join("\n");
  return {
    "rsc-entry.tsx": `// generated by cf-lite - do not edit. Runs in the \`rsc\` Vite environment (react-server condition).
import { renderToReadableStream, loadServerAction } from "@vitejs/plugin-rsc/rsc";
import { createRsc } from "cf-lite/modules/rsc-server";
import { RscBoundary } from "./rsc-boundary";
const rsc = createRsc({ render: renderToReadableStream as never, loadAction: loadServerAction as never, Boundary: RscBoundary, routes: {
${rows}
} });
export const flight = rsc.flight;
export const config = rsc.config;
export const action = rsc.action;
`,
    "rsc-boundary.tsx": `// generated by cf-lite - do not edit.
"use client";
import { Component, useEffect, type ComponentType, type ReactNode } from "react";

// notFound() / redirect() thrown AFTER the response started streaming cannot change the status line (docs/design/rsc.md): the Flight error
// carries a digest and this boundary degrades it - redirect = client navigation (+ meta refresh / link fallback), not-found = the not-found component.
const safe = (u: string) => { try { return /^https?:$/.test(new URL(u, "http://x").protocol); } catch { return false; } };
function Go({ url }: { url: string }) {
  useEffect(() => { if (safe(url)) window.location.replace(url); }, [url]);
  return safe(url) ? <><meta httpEquiv="refresh" content={"0;url=" + url} /><noscript><a href={url}>{url}</a></noscript></> : null;
}
export class RscBoundary extends Component<{ children?: ReactNode; notFound?: ReactNode; forbidden?: ReactNode; unauthorized?: ReactNode; error?: ComponentType<any> }, { e?: { digest?: string } }> {
  state: { e?: { digest?: string } } = {};
  static getDerivedStateFromError(e: { digest?: string }) { return { e }; }
  render() {
    const e = this.state.e;
    if (!e) return this.props.children;
    const d = e.digest;
    if (typeof d === "string" && d.startsWith("CFL_REDIRECT;")) return <Go url={d.slice(d.indexOf(";", 13) + 1)} />;
    if (d === "CFL_NOT_FOUND") return this.props.notFound ?? <main><h1>Not Found</h1></main>;
    if (d === "CFL_FORBIDDEN") return this.props.forbidden ?? <main><h1>Forbidden</h1></main>;
    if (d === "CFL_UNAUTHORIZED") return this.props.unauthorized ?? <main><h1>Unauthorized</h1></main>;
    const E = this.props.error;
    return E ? <E digest={d} /> : <main><h1>Something went wrong</h1>{d ? <p>digest {d}</p> : null}</main>;
  }
}
`,
    "rsc-browser.tsx": `// generated by cf-lite - do not edit.
import { createFromReadableStream, createFromFetch, setServerCallback } from "@vitejs/plugin-rsc/browser";
import { rscStream } from "rsc-html-stream/client";
import { startRsc } from "cf-lite/modules/rsc-client";
startRsc({ createFromReadableStream, createFromFetch, setServerCallback, rscStream, paths: ${JSON.stringify(rsc.map((p) => p.path))},
  // @ts-ignore import.meta.hot exists only under vite dev (stripped from the build)
  onUpdate: (cb) => { import.meta.hot?.on("rsc:update", cb); } });
`,
  };
}

export const pagesConvention = defineConvention<PageRoute[]>({
  name: "pages",
  scan: ({ root, adapter }) => {
    if (!adapter) {
      if (scanPages(root, "app/routes", [".tsx", ".jsx", ".vue", ".svelte"]).length) throw new Error(NO_UI);
      return [];
    }
    return scanPages(root, "app/routes", adapter.extensions);
  },
  emit: (pages, ctx) => {
    const ssr = pages.filter((p) => p.render === "ssr" || p.ssrFallback);
    const rsc = pages.filter((p) => p.render === "rsc");
    const layouts = [...new Set(ssr.flatMap((p) => p.layouts))];
    const bounds = [...new Set(ssr.flatMap((p) => BOUNDARY_KINDS.map((k) => p[k]).filter((x): x is string => !!x)))];
    const bn = (f?: string) => (f ? `b${bounds.indexOf(f)}` : undefined);
    const pre: string[] = [];
    if (ssr.some((p) => p.hasCache)) pre.push(`import { cacheRoute } from "cf-lite/modules/cache";`);
    if (ssr.some((p) => p.hasIsr)) pre.push(`import { isrRoute } from "cf-lite/modules/isr";`);
    // SSR islands: only apps that have `*.island.tsx` files get the wrapper (every other app's generated code is unchanged)
    const islands = !!ctx.adapter?.islands && ssr.length > 0 && discoverIslands(ctx.root, ctx.adapter).length > 0;
    if (islands) pre.push(`import { islandsRoute } from "cf-lite/islands-server";`);
    if (rsc.length) pre.push(`import { rscRoute, rscActionRoute } from "cf-lite/modules/rsc";`);
    if (ssr.length) pre.push(`import { ssr } from "cf-lite/server";`, `import * as ui from ${JSON.stringify(ctx.adapter?.server ?? "")};`);
    return {
      preImports: pre,
      imports: [
        ...ssr.map((p, i) => `import * as s${i} from ${JSON.stringify(imp(p.file))};`),
        ...layouts.map((l, i) => `import * as l${i} from ${JSON.stringify(imp(l))};`),
        ...bounds.map((f, i) => `import * as b${i} from ${JSON.stringify(imp(f))};`),
      ],
      app: [...rsc.map((p) => `  .get(${JSON.stringify(honoPath(p.path))}, rscRoute({ path: ${JSON.stringify(p.path)}${p.hasCache ? ", cache: true" : ""}${p.hasIsr ? ", isr: true" : ""}${p.rscNoJs ? ", js: false" : ""} }))\n  .post(${JSON.stringify(honoPath(p.path))}, rscActionRoute({ path: ${JSON.stringify(p.path)}${p.rscNoJs ? ", js: false" : ""} }))`), ...ssr.map((p, i) => {
        // Plain pages keep the historical minimal call shape; `path` (param/splat matching) and boundaries are added only when needed.
        const extra = [
          /\*/.test(p.path) ? `path: ${JSON.stringify(p.path)}` : "",
          ...BOUNDARY_KINDS.filter((k) => p[k]).map((k) => `${k}: ${bn(p[k])}`),
          p.ssrFallback ? "staticFirst: true" : "",
        ].filter(Boolean).map((x) => ", " + x).join("");
        const h0 = `ssr(s${i} as never, { ui, hydrate: ${p.hydrate}, layouts: [${p.layouts.map((l) => `l${layouts.indexOf(l)}`).join(", ")}] as never${extra} })`;
        const h = islands ? `islandsRoute(${h0}, { hydrate: ${p.hydrate} })` : h0;
        // isr (R2, global) sits inside cache (Cache API, per colo): a colo HIT never reaches R2.
        const inner = p.hasIsr ? `isrRoute(s${i} as never, ${h})` : h;
        const handler = p.hasCache ? `cacheRoute(s${i} as never, ${inner})` : inner;
        // Prerendered files are served at `/x/1/` (trailing slash), and Hono routes are strict: a static-first route answers both forms.
        // A route with `actions` also answers POST. The POST side is never wrapped in cacheRoute (mutations are never cached).
        if (p.hasActions) return `  .get(${JSON.stringify(honoPath(p.path))}, ${handler})\n  .post(${JSON.stringify(honoPath(p.path))}, ${h})`;
        if (p.ssrFallback) return `  .on("GET", [${JSON.stringify(honoPath(p.path))}, ${JSON.stringify(honoPath(p.path) + "/")}], ${handler})`;
        return `  .get(${JSON.stringify(honoPath(p.path))}, ${handler})`;
      })],
      files: { "routes.ts": genRoutes(pages), ...(rsc.length ? rscFiles(rsc) : {}) },
    };
  },
});
