/**
 * `/__preview` (docs/preview.md): discovers components and `*.states.ts` under `app/`, generates `.cf-lite/preview.ts` and mounts it
 * **in dev only**. The app imports the module behind `import.meta.env.DEV`, so the production Worker bundle has no trace of it and
 * `run_worker_first` never gains a `/__preview` entry (it is a dev-only glob, see `devWorkerFirst`).
 * Emits nothing when there is no UI adapter that can bind props, or nothing to preview.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { scanPreview, type PreviewEntry } from "../preview-scan.js";
import { discoverIslands } from "../vite-islands.js";
import type { MockFile } from "../mocks.js";
import { defineConvention } from "./types.js";
import { imp } from "./util.js";

export const PREVIEW_CONVENTION = "preview";
const SETUP = ["app/preview.setup.ts", "app/preview.setup.tsx", "app/preview.setup.js"];

export const previewConvention = defineConvention<PreviewEntry[]>({
  name: PREVIEW_CONVENTION,
  scan: ({ root, adapter }) => (adapter ? scanPreview(root, adapter.extensions) : []),
  emit: (items, ctx) => {
    if (!items.length || !ctx.adapter) return {};
    const setup = SETUP.find((f) => existsSync(join(ctx.root, f)));
    const islands = !!ctx.adapter.islands && discoverIslands(ctx.root, ctx.adapter).length > 0;
    const mocks = (ctx.entries["mocks"] as MockFile[] | undefined) ?? [];
    const rows = items.map((it) => `  { id: ${JSON.stringify(it.id)}, name: ${JSON.stringify(it.name)}, group: ${JSON.stringify(it.group)}, island: ${it.island}${it.file ? `, load: () => import(${JSON.stringify(imp(it.file))})` : ""}${it.states ? `, states: () => import(${JSON.stringify(imp(it.states))})` : ""} },`);
    const file = `// generated by cf-lite — do not edit. Dev only: loaded behind import.meta.env.DEV, never part of a production build.
import * as ui from ${JSON.stringify(ctx.adapter.server)};
import { createPreview } from "cf-lite/modules/preview";

declare const __CFL_MOCK__: boolean;

export default createPreview({
  ui: ui as never,
  items: [
${rows.join("\n")}
  ],${setup ? `\n  setup: ${JSON.stringify(setup)},` : ""}${islands ? "\n  islands: true," : ""}${mocks.length ? `\n  mocks: () => import("./mocks").then((m) => m.table),` : ""}
  mockOn: __CFL_MOCK__,
});
`;
    return {
      preImports: [`import type { MiddlewareHandler } from "hono";`],
      declarations: [`// dev only: \`import.meta.env.DEV\` is statically false in a build, so the dynamic import (and /__preview) is dropped\nconst previewGate: MiddlewareHandler = async (c, next) => {\n  if ((import.meta as unknown as { env: { DEV: boolean } }).env.DEV) return (await import("./preview")).default(c, next);\n  return next();\n};`],
      appPre: [`  .use("/__preview", previewGate)`, `  .use("/__preview/*", previewGate)`],
      files: { "preview.ts": file },
      devWorkerFirst: ["/__preview", "/__preview/*"],
    };
  },
});
