/**
 * `server/queues/<name>.ts` -> one multiplexed `queue()` handler (by `batch.queue`) + a typed producer `queues.<name>` in `.cf-lite/queues.ts`.
 *
 *   export type Message = { to: string };                 // -> queues.emails.send({ to })  is typed (else `unknown`)
 *   export const queue = "emails";                        // optional: Cloudflare queue name (default: the file name)
 *   export const binding = "EMAILS_QUEUE";                // optional: producer binding (default: <FILE_NAME>_QUEUE)
 *   export const schema = z.object({ to: z.string() });   // optional: anything with .parse(); validates on send, and types it
 *   export default defineQueue<Message>({ each: async (m, msg, env) => { ... }, retryDelay: backoff() });
 *   // or a raw handler: export default async (batch, env, ctx) => { ... }
 *
 * A dead-letter queue is just another file (`emails-dlq.ts`) whose `queue` is the DLQ name set in the consumer's `dead_letter_queue`.
 */
import { defineConvention } from "./types.js";
import { asArray, hasDefault, hasExport, imp, readString, scanJobDir, upperSnake } from "./jobs-util.js";

export interface QueueEntry { file: string; name: string; queue: string; binding: string; message: "type" | "schema" | "unknown"; hasDefault: boolean }

/** Dispatch table = the app's queue files + the generated ISR consumer (re-renders through `.cf-lite/app`). */
function isrHandlers(active: QueueEntry[]) {
  return {
    imports: [
      `import { dispatchQueue } from "cf-lite/modules/queue";`,
      `import { isrConsumer } from "cf-lite/modules/isr";`,
      `import app from "./app";`,
      ...active.map((q, i) => `import q${i} from ${JSON.stringify(imp(q.file))};`),
    ],
    queue: `(batch, env, ctx) => dispatchQueue({ ${[...active.map((q, i) => `${JSON.stringify(q.queue)}: q${i}`), `"isr": isrConsumer({ render: (req, e, x) => app.fetch(req, e, x) })`].join(", ")} }, batch, env, ctx)`,
  };
}
const isrConsumerCheck = (w: Record<string, unknown>): string[] =>
  (asArray((w.queues as { consumers?: unknown } | undefined)?.consumers) as { queue?: string }[]).some((c) => c.queue === "isr") ? [] : [`\`export const isr\` pages: wrangler \`queues.consumers\` has no entry for queue "isr" - regeneration messages are never processed`];

export const queuesConvention = defineConvention<QueueEntry[]>({
  name: "queues",
  scan: ({ root }) =>
    scanJobDir(root, "queues").map((f) => ({
      file: f.file,
      name: f.name,
      queue: readString(f.src, "queue") ?? f.name,
      binding: readString(f.src, "binding") ?? `${upperSnake(f.name)}_QUEUE`,
      message: hasExport(f.src, "type|interface") && /export\s+(?:type|interface)\s+Message\b/.test(f.src) ? "type" : /export\s+const\s+schema\b/.test(f.src) ? "schema" : "unknown",
      hasDefault: hasDefault(f.src),
    })),
  emit: (qs, ctx) => {
    // `export const isr` pages need the queue "isr" consumer: generated here unless the app brings its own `server/queues/isr.ts`.
    const pages = (ctx.entries["pages"] as { hasIsr?: boolean; render: string; ssrFallback?: boolean }[] | undefined) ?? [];
    const autoIsr = pages.some((p) => p.hasIsr && (p.render === "ssr" || p.render === "rsc" || p.ssrFallback)) && !qs.some((q) => q.queue === "isr");
    if (!qs.length) return autoIsr ? { handlers: isrHandlers([]), checks: [isrConsumerCheck] } : {};
    const seen = new Map<string, string>();
    for (const q of qs) {
      if (seen.has(q.queue)) throw new Error(`cf-lite: ${q.file} and ${seen.get(q.queue)} both handle queue "${q.queue}"`);
      seen.set(q.queue, q.file);
    }
    const active = qs.filter((q) => q.hasDefault);
    const prod = qs.map((q, i) => {
      const src = JSON.stringify(imp(q.file));
      const msg = q.message === "type" ? `import type { Message as M${i} } from ${src};` : q.message === "schema" ? `import { schema as S${i} } from ${src};\ntype M${i} = SchemaOutput<typeof S${i}>;` : `type M${i} = unknown;`;
      return { msg, line: `  ${JSON.stringify(q.name)}: queueProducer<M${i}>(() => (env as unknown as Env).${q.binding}${q.message === "schema" ? `, S${i}` : ""}),`, hasSchema: q.message === "schema" };
    });
    const queuesFile = [
      "// generated by cf-lite — do not edit",
      `import { env } from "cloudflare:workers";`,
      `import { queueProducer, type SchemaOutput } from "cf-lite/modules/queue";`,
      ...prod.map((p) => p.msg),
      "",
      "/** Typed producers: `await queues.<name>.send(message)`. Bindings come from the wrangler `queues.producers` entry. */",
      "export const queues = {",
      ...prod.map((p) => p.line),
      "};",
      "",
    ].join("\n");
    return {
      files: { "queues.ts": queuesFile },
      handlers: autoIsr ? isrHandlers(active) : active.length
        ? {
            imports: [`import { dispatchQueue } from "cf-lite/modules/queue";`, ...active.map((q, i) => `import q${i} from ${JSON.stringify(imp(q.file))};`)],
            queue: `(batch, env, ctx) => dispatchQueue({ ${active.map((q, i) => `${JSON.stringify(q.queue)}: q${i}`).join(", ")} }, batch, env, ctx)`,
          }
        : undefined,
      checks: [
        ...(autoIsr ? [isrConsumerCheck] : []),
        () => qs.filter((q) => !q.hasDefault).map((q) => `${q.file} has no default export (\`export default defineQueue({ each })\` or a \`(batch, env, ctx)\` handler)`),
        (w) => {
          const q = (w.queues ?? {}) as { producers?: unknown; consumers?: unknown };
          const producers = asArray(q.producers) as { binding?: string; queue?: string }[];
          const consumers = asArray(q.consumers) as { queue?: string }[];
          const out: string[] = [];
          for (const e of qs) {
            if (!producers.some((p) => p.binding === e.binding)) out.push(`${e.file}: wrangler \`queues.producers\` has no binding "${e.binding}" (queues.${e.name}.send() would throw) - run \`cf-lite add queue ${e.name}\``);
            if (e.hasDefault && !consumers.some((c) => c.queue === e.queue)) out.push(`${e.file}: wrangler \`queues.consumers\` has no entry for queue "${e.queue}" - its handler never runs`);
          }
          for (const c of consumers) if (c.queue && !seen.has(c.queue) && !(autoIsr && c.queue === "isr")) out.push(`wrangler \`queues.consumers\` lists "${c.queue}" but no server/queues file handles it - batches would fail`);
          return out;
        },
      ],
    };
  },
});
