/**
 * Route config (`redirects` / `rewrites` / `headers`, from `cfLite({ routeConf })`) -> a generated `.cf-lite/routeconf.ts` table plus one
 * Hono middleware at the very front of the app (redirect -> rewrite -> next -> response headers), and Worker-first globs for ONLY the
 * rules the assets layer cannot serve (conditional / rewrite / `:name+`). Static + placeholder redirects and unconditional headers are
 * compiled to `_redirects` / `_headers` by `../vite-routeconf.ts` and never wake the Worker. docs/route-config.md.
 * Not a built-in (it needs the user's config): `generate()` prepends it when `routeConf` is set.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { compileRouteConf, countUserRules, type CompiledRouteConf, type RouteConf } from "../config.js";
import { defineConvention } from "./types.js";

export const ROUTECONF_NAME = "routeconf";

const read = (root: string, f: string) => { const p = join(root, "public", f); return existsSync(p) ? readFileSync(p, "utf8") : undefined; };

export function routeconfConvention(conf: RouteConf) {
  return defineConvention<CompiledRouteConf>({
    name: ROUTECONF_NAME,
    scan: ({ root }) => {
      const u = countUserRules(read(root, "_redirects"), read(root, "_headers"));
      return compileRouteConf(conf, { reserved: { ...u, headerRules: u.headerRules + 1 /* default immutable /assets/* block */ } });
    },
    emit: (c) => {
      const t = c.table;
      if (!t.redirects.length && !t.rewrites.length && !t.headers.length) return {};
      return {
        files: { "routeconf.ts": `// generated by cf-lite — do not edit\nimport type { RouteTable } from "cf-lite/modules/routeconf";\n\nexport const table: RouteTable = ${JSON.stringify(t, null, 2)};\n` },
        imports: [`import { routeconfMiddleware } from "cf-lite/modules/routeconf";`, `import { table as rcTable } from "./routeconf";`],
        declarations: [`const rcSelf: Parameters<typeof routeconfMiddleware>[1] = {};`],
        appPre: [`  .use("*", routeconfMiddleware(rcTable, rcSelf) as never)`],
        exports: [`rcSelf.app = app;`],
        workerFirst: c.workerFirst,
      };
    },
  });
}
