/**
 * Typed routes: renders `.cf-lite/typed-routes.d.ts` from the page + handler route tables (docs/typegen.md).
 * The file augments `Register` in `cf-lite/href` so `href()`, `<Link to>`, `PageProps<"/x/:id">` know the app's real routes.
 * Runs after `pages` and `routes` (it reads their scan results); apps with no routes get no file (helpers fall back to `string`).
 */
import type { PageRoute, HandlerRoute } from "../scan.js";
import { defineConvention } from "./types.js";

/** `/blog/:slug` -> `{ slug: string }`; `/docs/*` -> `{ "*": string }`; `/docs/*?` -> `{ "*"?: string }`; `/` -> `{}`. */
export function paramsType(pattern: string): string {
  const props = pattern.split("/").filter(Boolean).flatMap((s) =>
    s === "*" ? [`"*": string`] : s === "*?" ? [`"*"?: string`] : s.startsWith(":") ? [`${JSON.stringify(s.slice(1))}: string`] : []);
  return props.length ? `{ ${props.join("; ")} }` : "{}";
}

/** Literal-type union of the concrete paths a pattern matches (`:x` and catch-alls become `${string}`). */
export function patternToTemplate(pattern: string): string[] {
  const segs = pattern.split("/").filter(Boolean);
  const build = (parts: string[]) => "`/" + parts.join("/") + "`";
  const parts: string[] = [];
  const out: string[] = [];
  for (const s of segs) {
    if (s === "*?") { out.push(build(parts.length ? parts : [])); parts.push("${string}"); out.push(build(parts)); return out.map((x) => x.replace(/^`\/`$/, '"/"')); }
    parts.push(s === "*" || s.startsWith(":") ? "${string}" : s);
  }
  out.push(build(parts));
  return out.map((x) => (x === "`/`" ? '"/"' : x));
}

const isTs = (f: string) => /\.(tsx?|jsx?)$/.test(f);
const modulePath = (f: string) => "../" + f.replace(/\.(tsx?|jsx?)$/, "");

export function renderRoutesDts(pages: PageRoute[], handlers: HandlerRoute[]): string | null {
  const routes = new Map<string, PageRoute | undefined>();
  for (const p of pages) routes.set(p.path, p);
  for (const h of handlers) {
    const path = h.mount.replace(/\/\*\??$/, "") || "/";
    if (!routes.has(path)) routes.set(path, undefined);
  }
  if (!routes.size) return null;
  const sorted = [...routes.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const q = JSON.stringify;
  const paramRows = sorted.map(([p]) => `    ${q(p)}: ${paramsType(p)};`);
  // Only the `loader` / `actions` members, never the whole module: `PageProps` is used by the page's own default export, and
  // `typeof import(whole module)` would make that type circular (TS silently degrades it to `any`).
  const modRows = sorted.filter(([, r]) => r && isTs(r.file) && (r.hasLoader || r.hasActions)).map(([p, r]) => {
    const m = `import(${q(modulePath(r!.file))})`;
    const members = [r!.hasLoader ? `loader: typeof ${m}["loader"]` : "", r!.hasActions ? `actions: typeof ${m}["actions"]` : ""].filter(Boolean);
    return `    ${q(p)}: { ${members.join("; ")} };`;
  });
  const tmpl = [...new Set(sorted.flatMap(([p]) => patternToTemplate(p)))];
  return [
    "// generated by cf-lite - do not edit",
    `import "cf-lite/href";`,
    "",
    `declare module "cf-lite/href" {`,
    "  interface Register {",
    "    routes: {",
    ...paramRows,
    "    };",
    "    modules: {",
    ...modRows,
    "    };",
    "    linkTo: LinkToInternal;",
    "  }",
    "}",
    "",
    "type RoutePath =",
    ...tmpl.map((t, i) => `  ${i ? "| " : "  "}${t}`),
    ";",
    "type Suffix = \"\" | \"/\" | `${\"\" | \"/\"}${\"?\" | \"#\"}${string}`;",
    "type LinkToInternal = `${RoutePath}${Suffix}` | `${\"http\" | \"https\"}://${string}` | `${\"mailto\" | \"tel\"}:${string}` | `#${string}` | `?${string}`;",
    "",
    "export {};",
    "",
  ].join("\n");
}

export const typegenConvention = defineConvention<null>({
  name: "typegen",
  scan: () => null,
  emit: (_e, ctx) => {
    const pages = (ctx.entries["pages"] as PageRoute[] | undefined) ?? [];
    const handlers = (ctx.entries["routes"] as HandlerRoute[] | undefined) ?? [];
    const dts = renderRoutesDts(pages, handlers);
    return dts ? { files: { "typed-routes.d.ts": dts } } : {};
  },
});
