/**
 * The convention-contributor contract (docs/conventions.md).
 *
 * A *convention* turns a file layout (`server/api/**`, `app/routes/**`, later `server/queues/**`, `middleware.ts`, ...) into
 * generated code. `generate()` runs every contributor: `scan(ctx)` reads the project, `emit(entries, ctx)` returns code chunks for
 * named slots of the generated files. A new convention is a new file under `conventions/` (built in) or an entry in
 * `cfLite({ conventions: [...] })` (yours) - never an edit of `generate.ts`.
 */
import type { UiAdapter } from "../adapter.js";

export interface ScanContext {
  /** Absolute project root. */
  root: string;
  /** The configured UI adapter, if any. */
  adapter?: UiAdapter;
}

/** What contributors have already found; `scan()` of later contributors can read earlier results (e.g. pages -> layouts). */
export interface EmitContext extends ScanContext {
  /** Entries returned by each contributor's `scan`, keyed by convention name. */
  entries: Record<string, unknown>;
}

/**
 * Slots of `.cf-lite/app.ts` (in the order they render) plus the extra generated files and build-time outputs.
 * Every field is optional; contributors are applied in registry order and their chunks concatenated.
 *
 *     // generated by cf-lite - do not edit
 *     import { Hono } from "hono";
 *     <preImports> <imports>
 *     <declarations>
 *     export const api = new Hono<{ Bindings: Env }>()  <api>  ;
 *     export type ApiType = typeof api;
 *     export const app = new Hono<{ Bindings: Env }>()  <appPre>  .route("/api", api)  <app>  ;
 *     <exports>
 *     export default app;
 */
export interface Emission {
  /** Import lines placed before everything in `imports` (shared library imports). */
  preImports?: string[];
  imports?: string[];
  /** Top-level statements between the imports and `export const api`. */
  declarations?: string[];
  /** Chain lines on the `api` Hono (e.g. `  .route("/x", a0)`). */
  api?: string[];
  /** Chain lines on `app` *before* `.route("/api", api)` - middleware, `.use(...)`. */
  appPre?: string[];
  /** Chain lines on `app` after `/api` - page routes, `.onError(...)`, ... Any Hono chain method works. */
  app?: string[];
  /** Top-level statements after the `app` chain, before `export default app`. */
  exports?: string[];
  /** Extra generated files under `.cf-lite/` (name -> full content). Written only when non-empty; a removed file is deleted. */
  files?: Record<string, string>;
  /** Non-fetch Worker handlers, merged into `.cf-lite/handlers.ts` (absent when no contributor provides any). */
  handlers?: HandlerSlots;
  /** Extra `assets.run_worker_first` globs (merged with the SSR route globs, deduplicated). */
  workerFirst?: string[];
  /** Like `workerFirst`, but only for `vite dev` (dev tools such as `/__preview`): never part of a production build's `run_worker_first`. */
  devWorkerFirst?: string[];
  /** Validators run against the parsed wrangler config; return human-readable warnings. */
  checks?: Array<(wrangler: Record<string, unknown>) => string[]>;
}

/** `.cf-lite/handlers.ts` exports `handlers`: `export default { fetch, ...handlers } satisfies ExportedHandler<Env>`. */
export interface HandlerSlots {
  /** Import lines for `handlers.ts` (paths relative to `.cf-lite/`). */
  imports?: string[];
  /** Expression source for each handler, e.g. `(batch, env, ctx) => q0.default(batch, env, ctx)`. */
  queue?: string;
  scheduled?: string;
  email?: string;
  tail?: string;
  trace?: string;
}

export interface Convention<E = unknown> {
  /** Unique id; also the key of `ctx.entries`. */
  name: string;
  scan(ctx: ScanContext): E;
  emit(entries: E, ctx: EmitContext): Emission;
}

export const defineConvention = <E>(c: Convention<E>): Convention<E> => c;
