/**
 * `server/workflows/<name>.ts` -> Worker-entry re-exports of the `WorkflowEntrypoint` classes (`.cf-lite/workflow-classes.ts`) and typed
 * `workflows.<name>.create({ params })` / `.get(id)` (`.cf-lite/workflows.ts`).
 *
 *   export default class Onboarding extends WorkflowEntrypoint<Env, { userId: string }> { async run(event, step) { ... } }
 *   export const className = "Onboarding";      // optional (default: PascalCase of the file name) - must equal wrangler `class_name`
 *   export const binding = "ONBOARDING_WORKFLOW"; // optional (default: <FILE_NAME>_WORKFLOW)
 *
 * In `server/worker.ts`:  `export * from "../.cf-lite/workflow-classes";`
 */
import { defineConvention } from "./types.js";
import { asArray, hasDefault, imp, pascal, readString, scanJobDir, upperSnake } from "./jobs-util.js";

export interface WorkflowEntry { file: string; name: string; className: string; binding: string; hasDefault: boolean }

export const workflowsConvention = defineConvention<WorkflowEntry[]>({
  name: "workflows",
  scan: ({ root }) =>
    scanJobDir(root, "workflows").map((f) => ({
      file: f.file,
      name: f.name,
      className: readString(f.src, "className") ?? pascal(f.name),
      binding: readString(f.src, "binding") ?? `${upperSnake(f.name)}_WORKFLOW`,
      hasDefault: hasDefault(f.src),
    })),
  emit: (ws) => {
    if (!ws.length) return {};
    const active = ws.filter((w) => w.hasDefault);
    const classes = [
      "// generated by cf-lite — do not edit",
      "// Workflow classes must be exported from the Worker entry: in server/worker.ts add  export * from \"../.cf-lite/workflow-classes\";",
      ...active.map((w) => `export { default as ${w.className} } from ${JSON.stringify(imp(w.file))};`),
      "",
    ].join("\n");
    const producers = [
      "// generated by cf-lite — do not edit",
      `import { env } from "cloudflare:workers";`,
      `import { workflowProducer, type WorkflowParams } from "cf-lite/modules/workflow";`,
      ...active.map((w, i) => `import type W${i} from ${JSON.stringify(imp(w.file))};`),
      "",
      "/** Typed producers: `await workflows.<name>.create({ params })`, `.get(id)`. Bindings come from the wrangler `workflows` entries. */",
      "export const workflows = {",
      ...active.map((w, i) => `  ${JSON.stringify(w.name)}: workflowProducer<WorkflowParams<typeof W${i}>>(() => (env as unknown as Env).${w.binding}),`),
      "};",
      "",
    ].join("\n");
    return {
      files: { "workflow-classes.ts": classes, "workflows.ts": producers },
      checks: [
        () => ws.filter((w) => !w.hasDefault).map((w) => `${w.file} has no default export (a class extending WorkflowEntrypoint)`),
        (w) => {
          const have = asArray(w.workflows) as { binding?: string; class_name?: string; name?: string }[];
          return ws.flatMap((e) => {
            const hit = have.find((h) => h.binding === e.binding);
            if (!hit) return [`${e.file}: wrangler \`workflows\` has no entry with binding "${e.binding}" (class_name "${e.className}") - run \`cf-lite add workflow ${e.name}\``];
            return hit.class_name === e.className ? [] : [`${e.file}: wrangler workflow "${e.binding}" has class_name "${hit.class_name}" but the generated export is "${e.className}"`];
          });
        },
      ],
    };
  },
});
